### ISSUE TITLE
Add support for "bw" lanes

### ISSUE THREAD

**Issue by BjornRasmussen** [kaart-labs/lane-connectivity_plugin#5]
I recently discovered this awesome plugin, so I started trying it out.  I ran into a small issue early on, however.
Most intersections worked fine with the plugin, but support for `both_ways` lanes was missing, and using them could crash the plugin.

**Comment by BjornRasmussen** [comment]
Here's the error message from JOSM:

{{{
Relative:URL: ^/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2020-06-30 19:13:42 +0200 (Tue, 30 Jun 2020)
Revision:16731
Build-Date:2020-07-01 01:30:51
URL:https://josm.openstreetmap.de/svn/trunk

Identification: JOSM/1.5 (16731 en) Windows 10 64-Bit
OS Build number: Windows 10 Pro 1903 (18362)
Memory Usage: 1147 MB / 1994 MB (673 MB allocated, but free)
Java version: 13.0.1+9, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Look and Feel: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
Screen: \Display0 1920x1080 (scaling 1.25x1.25)
Maximum Screen Size: 1920x1080
Best cursor sizes: 16x16 -> 32x32, 32x32 -> 32x32
Dataset consistency test: No problems found

Plugins:
+ FastDraw (35499)
+ PicLayer (35405)
+ apache-commons (35362)
+ buildings_tools (35500)
+ contourmerge (v0.1.6)
+ ejml (35313)
+ geotools (35169)
+ intersection (0.0.7)
+ jaxb (35092)
+ jts (35122)
+ opendata (35405)
+ reverter (35499)
+ tageditor (35258)
+ todo (30306)
+ turnlanes-tagging (283)
+ utilsplugin2 (35487)

Map paint styles:
+ https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Styles/iD&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features_ryg&zip=1

Last errors/warnings:
- E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 203 407 837 (no name).
- E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 203 407 837 (no name).
- E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 203 407 837 (no name).
- E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 203 407 837 (no name).
- E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 203 407 837 (no name).
- E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 203 407 837 (no name).
- E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 203 407 837 (no name).
- E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 203 407 837 (no name).
- E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 203 407 837 (no name).
- E: Handled by bug report queue: java.lang.NumberFormatException: For input string: "bw"


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (21) of main
java.lang.NumberFormatException: For input string: "bw"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:658)
	at java.base/java.lang.Integer.parseInt(Integer.java:776)
	at com.kaart.laneconnectivity.validation.ConnectivityRelationCheck.parseConnectivityTag(ConnectivityRelationCheck.java:67)
	at com.kaart.laneconnectivity.validation.ConnectivityRelationCheck.checkForInconsistentLanes(ConnectivityRelationCheck.java:100)
	at com.kaart.laneconnectivity.validation.ConnectivityRelationCheck.visit(ConnectivityRelationCheck.java:93)
	at org.openstreetmap.josm.data.osm.Relation.accept(Relation.java:176)
	at org.openstreetmap.josm.data.validation.Test.visit(Test.java:216)
	at org.openstreetmap.josm.actions.upload.ValidateUploadHook.checkUpload(ValidateUploadHook.java:66)
	at org.openstreetmap.josm.actions.UploadAction.lambda$checkPreUploadConditions$0(UploadAction.java:223)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.LinkedList$LLSpliterator.tryAdvance(LinkedList.java:1253)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:533)
	at org.openstreetmap.josm.actions.UploadAction.checkPreUploadConditions(UploadAction.java:223)
	at org.openstreetmap.josm.actions.UploadAction.uploadData(UploadAction.java:240)
	at org.openstreetmap.josm.actions.UploadAction.actionPerformed(UploadAction.java:296)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
}}}
