### ISSUE TITLE
Plugin crashes when you create really convoluted intersections

### ISSUE THREAD

**Issue by BjornRasmussen** [kaart-labs/lane-connectivity_plugin#6]
Was just dragging nodes around to improve road layouts when I accidentally created a shape the plugin, which was running in the background since I had the window open, didn't like.  Here's the exception:

```
{{{
Revision:17329
Is-Local-Build:true
Build-Date:2020-11-21 17:14:53

Identification: JOSM/1.5 (17329 SVN en) Linux Ubuntu 20.10
Memory Usage: 2896 MB / 5960 MB (1474 MB allocated, but free)
Java version: 15+36-Ubuntu-1, Private Build, OpenJDK 64-Bit Server VM
Look and Feel: com.formdev.flatlaf.FlatDarkLaf
Screen: :0.0 1920x1080 (scaling 1.0x1.0)
Maximum Screen Size: 1920x1080
Best cursor sizes: 16x16 -> 16x16, 32x32 -> 32x32
Desktop environment: ubuntu:GNOME
Environment variable LANG: en_US.UTF-8
libcommons-logging-java: libcommons-logging-java:-
fonts-noto: fonts-noto:-
Dataset consistency test: No problems found

Plugins:
+ Lanes (${version.entry.commit.revision})
+ flatlaf (35589)
+ intersection (0.0.7)
+ tageditor (35640)
+ turnlanes-tagging (288)
+ utilsplugin2 (35640)

Map paint styles:
+ https://josm.openstreetmap.de/josmfile?page=Styles/iD&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1

Last errors/warnings:
- 29116.502 E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 760 392 254 (Garrett Road).
- 29116.554 E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 760 392 254 (Garrett Road).
- 29116.577 E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 760 392 254 (Garrett Road).
- 29116.598 E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 760 392 254 (Garrett Road).
- 29117.165 E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 760 392 254 (Garrett Road).
- 29117.199 E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 760 392 254 (Garrett Road).
- 29117.225 E: com.kaart.laneconnectivity.model.UnexpectedDataException: All ways must be split at the intersection. Check way 760 392 254 (Garrett Road).
- 29132.769 E: Handled by bug report queue: java.lang.UnsupportedOperationException
- 29132.809 E: Handled by bug report queue: java.lang.UnsupportedOperationException
- 29156.438 E: Handled by bug report queue: java.lang.UnsupportedOperationException


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (20) of main
java.lang.UnsupportedOperationException
	at com.kaart.laneconnectivity.gui.Path$Start.offset(Path.java:526)
	at com.kaart.laneconnectivity.gui.LaneGui.recalculate(LaneGui.java:194)
	at com.kaart.laneconnectivity.gui.RoadGui.paintLanes(RoadGui.java:546)
	at com.kaart.laneconnectivity.gui.RoadGui.paintLanes(RoadGui.java:485)
	at com.kaart.laneconnectivity.gui.RoadGui.paint(RoadGui.java:405)
	at com.kaart.laneconnectivity.gui.JunctionPane.paintPassive(JunctionPane.java:459)
	at com.kaart.laneconnectivity.gui.JunctionPane.paintComponent(JunctionPane.java:399)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1884)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
}}}
```

**Comment by tsmock** [comment]
Sorry that its taken awhile to respond to this, but since we (Kaart) aren't actively using this plugin, and none of our clients are interested in it, I probably won't be able to fix this. Unless I have some spare time. I'll leave it open, so I hopefully don't forget, but please keep that in mind.

**Comment by BjornRasmussen** [comment]
That's fine.  I'm not currently using the plug-in either, but was testing the intersection shape building functionality when I encountered the bug.  I just thought it wouldn't hurt to report it.

**Comment by tsmock** [comment]
No problem. Thanks for reporting the bug (it lets us know that _someone_ is using it, even if we aren't).
